In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import collections
from matplotlib import cm
import tensorflow as tf
import keras

Using TensorFlow backend.


In [2]:
df = pd.read_csv("/Users/jaimefco/Documents/Smart Mobility/toy_example/data/countsDataframe.csv", index_col=0)

In [3]:
df.describe()

140           141           236           237           262  \
count  13104.000000  13104.000000  13104.000000  13104.000000  13104.000000   
mean      12.540140     15.437576     31.189255     27.371337     10.539606   
std        7.543351      9.261896     22.464035     19.613321      6.360110   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        5.000000      6.000000      8.000000      7.000000      5.000000   
50%       13.000000     17.000000     33.000000     29.000000     11.000000   
75%       19.000000     23.000000     50.000000     44.000000     15.000000   
max       37.000000     44.000000     93.000000     89.000000     35.000000   

                263  
count  13104.000000  
mean      12.903007  
std        7.585860  
min        0.000000  
25%        6.000000  
50%       14.000000  
75%       19.000000  
max       39.000000

In [4]:
df.tail()

140  141  236  237  262  263
7859400    8    9   12   12    9    8
7860000   12   12   13   11    8    7
7860600    9   10   11    9    5    8
7861200    7   10   11    7    6    6
7861800    6    9    9    8    4   10

In [5]:
df.head()

140  141  236  237  262  263
0       0    0    0    0    0    0
600     8   11   12   11    5   10
1200    6   10   14   13    7    9
1800    7   10    9    9    8    9
2400   10    8    8    7    4    6

In [6]:
7861800 / 3600 # Número de ejemplos que tendríamos

2183.8333333333335

In [7]:
2183 / 4 * 3 # Tamaño del conjunto de entrenamiento

1637.25

In [8]:
df.values.shape

(13104, 6)

In [9]:
13104 / 3

4368.0

In [10]:
X = []
y = []

In [11]:
for i in range(0, df.values.shape[0]-6, 3):
    X.append(df.values[i:i+6])
    y.append(df.values[i+6:i+9].flatten())

In [12]:
model = keras.Sequential()

model.add(keras.layers.LSTM(16, input_shape=(6, 6), unroll=True, return_sequences=True))
model.add(keras.layers.LSTM(16, unroll=True, return_sequences=True))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(32))
model.add(keras.layers.Dense(18))

model.summary() # To avoid warnings upgrade to tensorflow 1.5.0

W0822 10:31:37.482054 4576470464 deprecation_wrapper.py:119] From /Users/jaimefco/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0822 10:31:37.510993 4576470464 deprecation_wrapper.py:119] From /Users/jaimefco/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0822 10:31:37.516023 4576470464 deprecation_wrapper.py:119] From /Users/jaimefco/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 6, 16)             1472      
_________________________________________________________________
lstm_2 (LSTM)                (None, 6, 16)             2112      
_________________________________________________________________
flatten_1 (Flatten)          (None, 96)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                3104      
_________________________________________________________________
dense_2 (Dense)              (None, 18)                594       
Total params: 7,282
Trainable params: 7,282
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(loss='mean_squared_error', optimizer='rmsprop')

W0822 10:31:38.874412 4576470464 deprecation_wrapper.py:119] From /Users/jaimefco/venv/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



In [14]:
trainX = np.array(X)
trainX.shape

(4366, 6, 6)

In [15]:
trainY = np.array(y)
trainY.shape

(4366, 18)

In [27]:
history = model.fit(trainX[0:3493], trainY[0:3493],
                    epochs=180,
                    batch_size=64,
                    validation_data=(trainX[3493:], trainY[3493:]),
                    verbose=2)

Train on 3493 samples, validate on 873 samples
Epoch 1/20
 - 0s - loss: 13.2256 - val_loss: 16.1762
Epoch 2/20
 - 0s - loss: 13.3004 - val_loss: 15.3564
Epoch 3/20
 - 0s - loss: 13.2143 - val_loss: 18.8175
Epoch 4/20
 - 0s - loss: 13.2070 - val_loss: 14.9965
Epoch 5/20
 - 0s - loss: 13.2977 - val_loss: 15.4870
Epoch 6/20
 - 0s - loss: 13.3345 - val_loss: 16.1177
Epoch 7/20
 - 0s - loss: 13.2487 - val_loss: 15.2252
Epoch 8/20
 - 0s - loss: 13.3059 - val_loss: 15.3881
Epoch 9/20
 - 0s - loss: 13.1308 - val_loss: 16.7700
Epoch 10/20
 - 0s - loss: 13.2629 - val_loss: 15.5680
Epoch 11/20
 - 0s - loss: 13.0860 - val_loss: 17.6841
Epoch 12/20
 - 0s - loss: 13.1971 - val_loss: 16.1010
Epoch 13/20
 - 0s - loss: 13.1819 - val_loss: 15.0283
Epoch 14/20
 - 0s - loss: 13.2254 - val_loss: 15.1192
Epoch 15/20
 - 0s - loss: 13.0943 - val_loss: 15.8522
Epoch 16/20
 - 0s - loss: 13.1192 - val_loss: 15.4286
Epoch 17/20
 - 0s - loss: 13.0713 - val_loss: 15.1807
Epoch 18/20
 - 0s - loss: 13.0992 - val_loss

In [28]:
aa = model.predict(trainX[3493:])
aa = np.round(aa)

In [29]:
D = np.abs(trainY[3493:] - aa) #/ (trainY[5239:]+0.0000001)

In [30]:
aa

array([[23., 28., 62., ..., 51., 19., 22.],
       [22., 26., 58., ..., 48., 18., 22.],
       [18., 23., 48., ..., 39., 14., 19.],
       ...,
       [ 9., 12., 18., ..., 14.,  8., 10.],
       [ 8., 10., 13., ...,  9.,  6.,  8.],
       [ 8.,  9., 12., ...,  8.,  6.,  8.]], dtype=float32)

In [31]:
D

array([[2., 6., 8., ..., 1., 3., 3.],
       [3., 0., 5., ..., 1., 3., 1.],
       [3., 1., 8., ..., 0., 2., 1.],
       ...,
       [1., 3., 2., ..., 1., 3., 0.],
       [0., 1., 3., ..., 2., 2., 1.],
       [1., 1., 1., ..., 0., 2., 2.]])

In [32]:
print("Mean: {0}, Std: {1}.".format(D.mean(), D.std()))

Mean: 2.7111492936235204, Std: 3.0614377063844307.


**The worse case**

In [33]:
D[D.argmax()//18].reshape(3,6)

array([[ 3.,  1.,  0.,  7.,  2.,  4.],
       [ 4.,  8., 10.,  8.,  2.,  1.],
       [ 9.,  7., 25., 31.,  0.,  4.]])

In [34]:
aa[D.argmax()//18].reshape(3,6)

array([[18., 19., 38., 34., 14., 15.],
       [17., 19., 41., 35., 14., 16.],
       [19., 21., 46., 40., 15., 16.]], dtype=float32)

In [35]:
trainY[3493 + D.argmax()//18].reshape(3,6)

array([[21, 18, 38, 27, 12, 11],
       [21, 27, 51, 43, 16, 15],
       [28, 28, 71, 71, 15, 20]])

In [36]:
trainX[3493 + D.argmax()//18]

array([[10,  9, 10, 11,  8,  6],
       [ 7,  8, 18, 13,  8,  6],
       [17, 12, 27, 20, 14,  9],
       [13, 16, 31, 27, 12, 14],
       [15, 14, 26, 21,  7, 12],
       [19, 15, 32, 22, 16, 13]])